# web port
server:
#  port: ${server.port}
  port: 8081

# log config
logging:
  config: classpath:logback.xml
  path: ${DATA_PATH:.}/applogs/executor/jobhandler
#  path: ./data/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:8080
#      addresses: http://127.0.0.1:${datax.admin.port}
    executor:
      appname: datax-executor
      ip:
      port: 9999
#      port: ${executor.port:9999}
      ### job log path
#      logpath: ./data/applogs/executor/jobhandler
      logpath: ${DATA_PATH:.}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
#    jsonpath: /Users/ryan/data/applogs
    jsonpath: ${JSON_PATH:.}

  pypath: /Users/ryan/work/myteam/health/data-transfer/datax/target/datax/datax/bin/datax.py
#  pypath: ${python.path}
